"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sshIdleTimeoutMs = exports.isSshIdleTimeout = exports.SSH_IDLE_TIMEOUT_VALUES = exports.normalizeThemeId = exports.getXtermTheme = exports.THEME_IDS = exports.detectPlatformFromText = exports.resolveHostPlatform = exports.HOST_PLATFORM_ICONS = exports.getHostPlatformIcon = exports.HOST_PLATFORM_LABELS = exports.HOST_PLATFORMS = void 0;
var hostPlatform_1 = require("./hostPlatform");
Object.defineProperty(exports, "HOST_PLATFORMS", { enumerable: true, get: function () { return hostPlatform_1.HOST_PLATFORMS; } });
Object.defineProperty(exports, "HOST_PLATFORM_LABELS", { enumerable: true, get: function () { return hostPlatform_1.HOST_PLATFORM_LABELS; } });
var platformIcons_1 = require("./platformIcons");
Object.defineProperty(exports, "getHostPlatformIcon", { enumerable: true, get: function () { return platformIcons_1.getHostPlatformIcon; } });
Object.defineProperty(exports, "HOST_PLATFORM_ICONS", { enumerable: true, get: function () { return platformIcons_1.HOST_PLATFORM_ICONS; } });
var resolveHostPlatform_1 = require("./resolveHostPlatform");
Object.defineProperty(exports, "resolveHostPlatform", { enumerable: true, get: function () { return resolveHostPlatform_1.resolveHostPlatform; } });
var detectPlatform_1 = require("./detectPlatform");
Object.defineProperty(exports, "detectPlatformFromText", { enumerable: true, get: function () { return detectPlatform_1.detectPlatformFromText; } });
var themes_1 = require("./themes");
Object.defineProperty(exports, "THEME_IDS", { enumerable: true, get: function () { return themes_1.THEME_IDS; } });
Object.defineProperty(exports, "getXtermTheme", { enumerable: true, get: function () { return themes_1.getXtermTheme; } });
Object.defineProperty(exports, "normalizeThemeId", { enumerable: true, get: function () { return themes_1.normalizeThemeId; } });
var sshIdle_1 = require("./sshIdle");
Object.defineProperty(exports, "SSH_IDLE_TIMEOUT_VALUES", { enumerable: true, get: function () { return sshIdle_1.SSH_IDLE_TIMEOUT_VALUES; } });
Object.defineProperty(exports, "isSshIdleTimeout", { enumerable: true, get: function () { return sshIdle_1.isSshIdleTimeout; } });
Object.defineProperty(exports, "sshIdleTimeoutMs", { enumerable: true, get: function () { return sshIdle_1.sshIdleTimeoutMs; } });
//# sourceMappingURL=index.js.map